name: Code Mistake
description: File an issue with one of the code repositories.
labels: ["code-bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please ensure that the bug has not already been filed in the issue tracker.

        Thanks for taking the time to report this bug!
  - type: dropdown
    attributes:
      label: Section
      description: Which Section is this an issue for?
      multiple: false
      options:
        - Section 1 | Blockchain Basics
        - Section 2 | Simple Storage
        - Section 3 | Storage Factory
        - Section 4 | Fund Me
        - Section 5 | AI Prompting
        - Section 6 | Foundry Simple Storage
        - Section 7 | Foundry Fund Me
        - Section 8 | HTML/JS
        - Section 9 | Smart Contract Lottery
        - Section 10 | ERC20s
        - Section 11 | NFTs
        - Section 12 | Stablecoin
        - Section 13 | Merkle Tress
        - Section 14 | Upgrades
        - Section 15 | Account Abstraction
        - Section 16 | DAOs
        - Section 17 | Security Introduction
        - Other (please describe)
    validations:
      required: true
  - type: input
    attributes:
      label: Could you please leave a link to the Cyfrin Updraft Lesson (or YouTube video timestamp) where this error occurs? (You can right click a video and "copy video URL at current time")
      placeholder: "https://updraft.cyfrin.io/courses/foundry/foundry-simple-storage/introduction-foundry-simple-storage?lesson_format=video"
  - type: dropdown
    attributes:
      label: Operating System
      description: What operating system are you on?
      options:
        - Windows
        - macOS (Intel)
        - macOS (Apple Silicon)
        - Linux
  - type: textarea
    attributes:
      label: Describe the bug
      description: Please include relevant code snippets as well if relevant. Remember to format!
    validations:
      required: true
